name: rubytest
on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: '3.0'
      - name: jalankan testing
        run: rake test
